-- Canto Learning: vocabulary and learner progress
-- Run this migration in a Supabase project before importing data/words.json.

create extension if not exists pgcrypto;

create table public.themes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.words (
  id bigint generated by default as identity primary key,
  legacy_id integer unique,
  theme_id bigint not null references public.themes(id) on delete restrict,
  word text not null,
  jyutping text not null,
  difficulty smallint not null check (difficulty between 1 and 5),
  level text not null,
  meaning_zh text,
  meaning_en text,
  pronunciation_note text,
  audio_status text not null default 'unreviewed' check (audio_status in ('unreviewed', 'verified', 'needs_review')),
  audio_review_note text,
  audio_female text,
  audio_male text,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (word, jyutping)
);

create table public.examples (
  id bigint generated by default as identity primary key,
  word_id bigint not null references public.words(id) on delete cascade,
  sentence text not null,
  jyutping text,
  translation_zh text,
  translation_en text,
  audio_path text,
  is_hong_kong_local boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.tags (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table public.word_tags (
  word_id bigint not null references public.words(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (word_id, tag_id)
);

create table public.user_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id bigint not null references public.words(id) on delete cascade,
  status text not null default 'new' check (status in ('new', 'learning', 'review', 'mastered')),
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  next_review_at timestamptz,
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, word_id)
);

create table public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id bigint references public.words(id) on delete set null,
  question_type text not null,
  submitted_answer text,
  is_correct boolean not null,
  response_ms integer check (response_ms is null or response_ms >= 0),
  created_at timestamptz not null default now()
);

create index words_theme_difficulty_idx on public.words(theme_id, difficulty);
create index examples_word_idx on public.examples(word_id);
create index user_progress_review_idx on public.user_progress(user_id, next_review_at);
create index quiz_attempts_user_created_idx on public.quiz_attempts(user_id, created_at desc);

alter table public.themes enable row level security;
alter table public.words enable row level security;
alter table public.examples enable row level security;
alter table public.tags enable row level security;
alter table public.word_tags enable row level security;
alter table public.user_progress enable row level security;
alter table public.quiz_attempts enable row level security;

create policy "Published themes are readable" on public.themes for select using (true);
create policy "Published words are readable" on public.words for select using (is_published);
create policy "Published examples are readable" on public.examples for select using (
  exists (select 1 from public.words where words.id = examples.word_id and words.is_published)
);
create policy "Tags are readable" on public.tags for select using (true);
create policy "Word tags are readable" on public.word_tags for select using (true);

create policy "Users read own progress" on public.user_progress
  for select using (auth.uid() = user_id);
create policy "Users create own progress" on public.user_progress
  for insert with check (auth.uid() = user_id);
create policy "Users update own progress" on public.user_progress
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users delete own progress" on public.user_progress
  for delete using (auth.uid() = user_id);

create policy "Users read own attempts" on public.quiz_attempts
  for select using (auth.uid() = user_id);
create policy "Users create own attempts" on public.quiz_attempts
  for insert with check (auth.uid() = user_id);
